#!/bin/sh

set -eo pipefail

REGISTRY_PATH=/bin/registry
PAX_FLAGS="emr"

# Set file attributes for PaX
setfattr -n user.pax.flags -v ${PAX_FLAGS} ${REGISTRY_PATH}

case "$1" in
    *.yaml|*.yml) set -- ${REGISTRY_PATH} serve "$@" ;;
    serve|garbage-collect|help|-*) set -- ${REGISTRY_PATH} "$@" ;;
esac

exec "$@"
